global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'web'
    metrics_path: /    
    static_configs:
      - targets: ['web-frontend:80']